using UnityEditor;
using UnityEngine;
using AsterionGame;
public static class HunterLoadoutSetup {
 public static void Configure(PlayerClassDefinition hunter){
  if(hunter.loadoutVersion>=6)return;
  var twinPulses=AssetDatabase.LoadAssetAtPath<LaserAbility>("Assets/Abilities/TwinPulses.asset");
  twinPulses.displayName="Twin Pulses";
  twinPulses.description="1 s Cast. Zwei Schuesse mit je 10 Schaden. Erzeugt 8 Energie pro Cast. 10% Chance, den Cooldown von Pulse Kick zurueckzusetzen.";
  twinPulses.cooldown=0f;
  twinPulses.castTime=1f;
  twinPulses.damage=10f;
  twinPulses.energyOnHit=0f;
  twinPulses.energyOnCast=8f;
  twinPulses.kickResetChance=0.1f;
  EditorUtility.SetDirty(twinPulses);
  var jetBurst=AssetDatabase.LoadAssetAtPath<DashAbility>("Assets/Abilities/JetBurst.asset");
  jetBurst.displayName="Jetpack Boost";
  jetBurst.description="8 m Jetpack-Schub in Bewegungsrichtung. Zauber koennen waehrend des Schubs gewirkt werden; laufende Casts bleiben erhalten.";
  jetBurst.cooldown=5f;
  jetBurst.range=8f;
  jetBurst.travelSpeed=12f;
  jetBurst.jetAssisted=true;
  jetBurst.energyCost=0f;
  EditorUtility.SetDirty(jetBurst);
  var hunterGrenade=AssetDatabase.LoadAssetAtPath<GrenadeAbility>("Assets/Abilities/HunterGrenade.asset");
  hunterGrenade.description="Boden waehlen und bestaetigen. 15 Flaechenschaden; alle Getroffenen erhalten 15 s lang 6 Ion-Schaden/s und 50% Slow. Jeder Treffer und DoT-Tick erzeugt 3 Energie pro Gegner. Jeder DoT-Tick hat 15% Chance auf Charged Shot: sofort und +20% Schaden.";
  hunterGrenade.cooldown=8f;
  hunterGrenade.energyCost=0f;
  hunterGrenade.energyOnHit=3f;
  hunterGrenade.groundTargeted=true;
  hunterGrenade.dotEnergyGain=3f;
  hunterGrenade.dotProcChance=0.15f;
  EditorUtility.SetDirty(hunterGrenade);
  var pulseKick=AssetDatabase.LoadAssetAtPath<KickAbility>("Assets/Abilities/PulseKick.asset");
  pulseKick.description="Richtung waehlen und bestaetigen. Kurzer Vorstoss mit Kick, 35 Schaden, 2 s Betaeubung und 8 Energie pro Treffer. Twin Pulses kann den Cooldown zuruecksetzen.";
  pulseKick.cooldown=20f;
  EditorUtility.SetDirty(pulseKick);
  var explosiveShot=AssetDatabase.LoadAssetAtPath<ExplosiveShotAbility>("Assets/Abilities/ExplosiveShot.asset");
  if(!explosiveShot){explosiveShot=ScriptableObject.CreateInstance<ExplosiveShotAbility>();AssetDatabase.CreateAsset(explosiveShot,"Assets/Abilities/ExplosiveShot.asset");}
  explosiveShot.displayName="Explosive Shot";
  explosiveShot.description="Feuert ein zielverfolgendes Projektil auf den ausgewaehlten Gegner. Beim Treffer erleiden das Ziel und alle Gegner im Umkreis von 2,8 m jeweils 70 Schaden. Kostenlos. Hindernisse stoppen das Projektil.";
  explosiveShot.cooldown=5f;
  explosiveShot.castTime=0f;
  explosiveShot.range=19f;
  explosiveShot.damage=70f;
  explosiveShot.energyCost=0f;
  explosiveShot.energyOnHit=0f;
  explosiveShot.energyOnCast=0f;
  explosiveShot.energyFraction=0f;
  explosiveShot.channelDuration=0f;
  explosiveShot.channelTickInterval=0.2f;
  explosiveShot.lockMovement=false;
  explosiveShot.radius=2.8f;
  explosiveShot.projectileSpeed=26f;
  EditorUtility.SetDirty(explosiveShot);
  var chargedShot=AssetDatabase.LoadAssetAtPath<ChargedShotAbility>("Assets/Abilities/ChargedShot.asset");
  chargedShot.description="1,5 s Cast im Stand, 180 Schaden, 30 Energie. Ion-Overcharge macht den naechsten Cast sofort und verstaerkt ihn um 20% auf 216 Schaden; er umgeht den eigenen Cooldown. Jetpack ist waehrend des Casts nutzbar.";
  chargedShot.castTime=1.5f;
  chargedShot.energyCost=30f;
  chargedShot.energyOnHit=0f;
  chargedShot.damage=180f;
  EditorUtility.SetDirty(chargedShot);
  var aegisShield=AssetDatabase.LoadAssetAtPath<ShieldAbility>("Assets/Abilities/AegisShield.asset");
  aegisShield.description="5 s lang 50% weniger eingehender Schaden. C mit Maus ueber einem Verbuendeten schuetzt diesen (20 m); sonst dich selbst. Kostet 15 Energie.";
  aegisShield.cooldown=30f;
  aegisShield.duration=5f;
  aegisShield.reduction=0.5f;
  aegisShield.canTargetAllies=true;
  aegisShield.range=20f;
  EditorUtility.SetDirty(aegisShield);
  var overdrive=AssetDatabase.LoadAssetAtPath<UltimateAbility>("Assets/Abilities/Overdrive.asset");
  overdrive.description="Richtung waehlen und bestaetigen. Kanalisiert 3 s eine Salve aus beiden Waffen in einen 80-Grad-Kegel (20 m): 15 Wellen mit je 40 Schaden. Ab Kanalstart 15 s lang 30% kuerzere Castzeiten und +50% Lauftempo. Kostet 75 Energie.";
  overdrive.range=20f;
  overdrive.damage=40f;
  overdrive.channelDuration=3f;
  overdrive.channelTickInterval=0.2f;
  overdrive.coneAngle=80f;
  overdrive.buffDuration=15f;
  EditorUtility.SetDirty(overdrive);
  hunter.abilities=new AbilityDefinition[]{twinPulses,jetBurst,hunterGrenade,pulseKick,explosiveShot,chargedShot,aegisShield,overdrive};
  hunter.buildEnergyOnHits=true;hunter.loadoutVersion=6;EditorUtility.SetDirty(hunter);
 }
}
